global:
  scrape_interval: "15s"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ['localhost:9090']
        
  - job_name: "node"
    static_configs:
      - targets: ['node-exporter:9100']
        labels: 
          instance: 'Slave-1'
      - targets: ['172.31.10.134:9100']
        labels:
          instance: 'Slave-2'
  
  - job_name: "containers"
    static_configs:
      - targets: ['172.31.4.245:9323']
        labels:
          instance: 'web-app'

  - job_name: "jenkins"
    metrics_path: "/prometheus"
    static_configs:
      - targets: ['172.31.6.60:8080']
        labels:
          instance: 'jenkins-master'